inherit_from:
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop.yml
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop-performance.yml
  - https://raw.githubusercontent.com/omu/omu/master/etc/rubocop/rubocop-minitest.yml

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - lib/omu/sms/provider/*

AllCops:
  TargetRubyVersion: 2.5
